# Generated by Django 3.0.13 on 2021-03-05 16:33

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_auto_20210305_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tipo de reporte')),
                ('reference', models.CharField(max_length=20, verbose_name='referencia')),
                ('created', models.DateTimeField(verbose_name='creado')),
                ('updated', models.DateTimeField(verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'tipo de reporte',
                'verbose_name_plural': 'tipos de reporte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Reporte')),
                ('reference', models.CharField(max_length=50, verbose_name='referencia')),
                ('component', models.CharField(max_length=200, verbose_name='componente')),
                ('document', models.FileField(upload_to=reports.models.get_document_filepath, verbose_name='documento')),
                ('inspection_date', models.DateField(verbose_name='fecha de inspeccion')),
                ('next_inspection_date', models.DateField(verbose_name='fecha de proxima inspeccion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Office', verbose_name='Oficina')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportType', verbose_name='tipo de reporte')),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'ordering': ['-created'],
            },
        ),
    ]
